### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lolucodes** [JamesWoolfenden/terraform-aws-cassandra#18]
Error: Error launching source instance: InvalidParameterValue: Address 172.31.0.16 does not fall within the subnet's address range
│       status code: 400, request id: 38b06bb7-76ee-4b0a-adbd-12437adb7863
│ 
│   with module.cassandra.aws_instance.cassandra[2],
│   on ../../aws_instance.cassandra.tf line 1, in resource "aws_instance" "cassandra":
│    1: resource "aws_instance" "cassandra" {

module "cassandra" {
  source        = "../../"
  instance_type = "t3.micro"
  subnet_ids    = ["subnet-068e276477c82b451", "subnet-0fb3e11f3fc472fb8", "subnet-01dcfb5e8edf5edeb"]
  #add the private ips
  private_ips       = local.private_ips
  allowed_ranges    = ["172.31.0.0/16"]
  ssh-inbound-range = ["172.31.0.0/16"]
  ami               = local.ami
  vpc_id            = var.vpc_id
}

module "myip" {
  source  = "jameswoolfenden/ip/http"
  version = "0.2.7"
}

# locals {
#   private_ips = [cidrhost(data.aws_subnet.a.cidr_block, 14), cidrhost(data.aws_subnet.a.cidr_block, 15), cidrhost(data.aws_subnet.a.cidr_block, 16)]
# }

locals {
  private_ips = ["172.31.0.14", "172.31.0.15", "172.31.0.16"]
}

**Comment by JamesWoolfenden** [comment]
Have you got very small subnets?

**Comment by lolucodes** [comment]
No The issue was the instances were getting created in the same subnet 

data "aws_subnet" "subnet1" {
    id = tolist(data.aws_subnets.myawesomesubnets.ids)[0]
}

data "aws_subnet" "subnet2" {
    id = tolist(data.aws_subnets.myawesomesubnets.ids)[1]
}

data "aws_subnet" "subnet3" {
    id = tolist(data.aws_subnets.myawesomesubnets.ids)[2]
}
locals {
  private_ips = [cidrhost(data.aws_subnet.subnet1.cidr_block, 14), cidrhost(data.aws_subnet.subnet2.cidr_block, 15), cidrhost(data.aws_subnet.subnet3.cidr_block, 16)]
}

this fix worked for me
